routes/web.php
<?php
use App\SubDistrict;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProfileController;

Route::get('/', 'WelcomeController@index')->name('/');

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
Route::group(['middleware' => ['web','auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
});

Route::get('/home', function(){
    if(Auth::user()->admin == 0)
    {
        return redirect()->action('WelcomeController@index');
    } 
    else 
    {
        return view('admin');
    }
})->name('home');

/* Announcement/Pengumuman */
Route::group(['prefix' => 'announcement'], function(){
    Route::get('/showAll', 'AnnouncementController@showAll')->name('announcement.showAll');
    Route::get('/showById/{id}', 'AnnouncementController@showById')->name('announcement.showById');
});
Route::resource('announcement', 'AnnouncementController');

/* Profile */
Route::group(['prefix' => 'profile'], function () {
    Route::get('/pkh', 'ProfileController@showPkh')->name('profile.pkh');
    Route::get('/visimisi', 'ProfileController@showVisiMisi')->name('profile.visimisi');
    Route::get('/tugasfungsi', 'ProfileController@showTugasFungsi')->name('profile.tugasfungsi'); 
    Route::get('/createNew/{jenis}', 'ProfileController@createNew')->name('profile.createNew');
});

Route::resource('profile', 'ProfileController');

/* Human Resource/SDM */
Route::resource('humanresource', 'HumanResourceController');
Route::get('/humanresource/detail/{id}', 'HumanResourceController@detail')->name('humanresource.detail');

/* Sub District/Kecamatan */
Route::resource('subdistrict', 'SubDistrictController');

/* Activity/Kegiatan */
Route::resource('activity', 'ActivityController');
Route::get('/activity/showById/{id}', 'ActivityController@showById')->name('activity.showById');
Route::patch('activity/updateStatus/{id}', 'ActivityController@updateStatus')->name('activity.updateStatus');

/* Comment/Komentar Kegiatan */
Route::resource('activitycomment', 'ActivityCommentController');

/* News/Berita */


Route::group(['prefix' => 'news'], function () {
    Route::get('/showAll', 'NewsController@showAll')->name('news.showAll');
    Route::get('/showById/{id}', 'NewsController@showById')->name('news.showById');
    Route::patch('/updateStatus/{id}', 'NewsController@updateStatus')->name('news.updateStatus');
});
Route::resource('news', 'NewsController');
Route::post('news/storeCategory', 'NewsController@storeCategory')->name('news.storeCategory');

/* Category/Kategori */
Route::patch('/category/storeNew', 'CategoryController@storeNew')->name('category.storeNew');
Route::resource('category', 'CategoryController');

/* Comment/Komentar Berita */
Route::resource('newscomment', 'NewsCommentController');

/* Product/Pemberdayaan Ekonomi (Produk) */
Route::get('/product/showAll', 'ProductController@showAll')->name('product.showAll');
Route::resource('product', 'ProductController');

/* Complaint/Sistem Pengaduan */
Route::group(['prefix' => 'complaint'], function () {
    Route::get('/formComplaint', 'ComplaintController@form')->name('complaint.formComplaint');
    Route::get('/getVillage/{id}', 'ComplaintController@getVillage')->name('complaint.getVillage');
});
Route::resource('complaint', 'ComplaintController');

/* Kontak/Contact */
Route::get('/contact/map', 'ContactController@showMap')->name('contact.map');
Route::resource('contact', 'ContactController');

/* Employee/Karyawan */
// Route::group(['prefix' => 'employee'], function () {
//     Route::get('/listByDistrict', 'EmployeeController@listByDistrict')->name('employee.listByDistrict');
//     Route::get('/detail/{id}', 'EmployeeController@detail')->name('employee.detail'); 
// });
Route::get('/employee/detail/{id}', 'EmployeeController@detail')->name('employee.detail');
Route::get('/employee/createNew/{id}', 'EmployeeController@createNew')->name('employee.createNew');
Route::get('/employee/getVillage/{id}', 'EmployeeController@getVillage')->name('employee.getVillage');
Route::resource('employee', 'EmployeeController');

/* Video */
Route::resource('video', 'VideoController');

/* Village */
Route::get('/village/createNew/{id}', 'VillageController@createNew')->name('village.createNew');
Route::resource('village', 'VillageController');

/* KPM atau PESERTA PKH */
Route::group(['prefix' => 'participant'], function () {
    Route::get('/showDataTahapI', 'ParticipantController@showDataTahapI')->name('participant.showDataTahapI');
    Route::get('/getVillage/{id}', 'ParticipantController@getVillage')->name('participant.getVillage');
});
Route::resource('participant', 'ParticipantController');

/* Download */
Route::get('/download/showDownload', 'DownloadController@showDownload')->name('download.showDownload');
Route::resource('download', 'DownloadController');
Route::get('/download/{uuid}/download', 'DownloadController@download')->name('download.download');

app/Announcement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Announcement extends Model
{
    protected $fillable =
    [
        'judul','deskripsi','admin_id'
    ];
    
    public function getCreatedAtAttribute()
    {
        return \Carbon\Carbon::parse($this->attributes['created_at'])->format('d, M Y H:i');
    }
    
    public function getUpdatedAtAttribute()
    {
        return \Carbon\Carbon::parse($this->attributes['updated_at'])->diffForHumans();
    }
}

app/Http/Controllers/AnnouncementController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Announcement;

class AnnouncementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $announ = Announcement::orderBy('created_at', 'desc')->paginate(10);
        return view('announcement.index', compact('announ'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('announcement.formCreate');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'judul' => 'required|string|max:255', 
            'deskripsi' => 'required'
        ]);

        $announ = new Announcement([
            'judul' => $request->get('judul'),
            'deskripsi' => $request->get('deskripsi'),
            'admin_id' => Auth::id()
        ]);
        $announ->save();
        return back()->with('success','Pengumuman Baru berhasil ditambahkan !');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $announ = Announcement::where('id', $id)->first();
        return view('announcement.formEdit', compact('announ')); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'judul' => 'required|string|max:255', 
            'deskripsi' => 'required'
        ]);

        $announ = Announcement::find($id);
        $announ->judul = $request->get('judul');
        $announ->deskripsi = $request->get('deskripsi');
        $announ->admin_id = Auth::id();

        try {
            $announ->save();
            return redirect()->route('announcement.index')->with('success','Pengumuman berhasil diupdate !');
        }
        catch (\Exception $e) { 
            return back()->with('error','Pengumuman gagal diupdate !');
        }         
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Announcement::destroy($id);
        return back()->with('success', 'Pengumuman berhasil dihapus!');
    }

    public function showById($id)
    {
        // Ambil Data Berita
        $ann = Announcement::find($id); 
        return view('announcement.showById', compact('ann'));
    }

    public function showAll()
    {
        // Ambil Semua Data Pengumuman
        $announcement = Announcement::orderBy('created_at', 'asc')->paginate(10); 

        return view('announcement.showAll', compact('announcement'));
    }
}

resources/views/announcement/formCreate.blade.php
@extends('layouts.admin')

@section('title')
    Post Pengumuman Baru
@endsection

@section('content')
<div class="content-wrapper">
    <div class="row">
        <div class="col-md-12">
                @if ($message = Session::get('success'))
                <div class="flash-message">
                    <p class="alert alert-success">{{ $message }}  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
                </div>
                @endif
        </div>
        
            
        <div class="col-md-12 grid-margin stretch-card">
                
            <div class="card">
                <div class="card-body">
                <h4 class="card-title">Pengumuman | Post Pengumuman Baru</h4>
                <form class="forms-sample" action="{{ route('announcement.store') }}" method="POST">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="judul">Judul</label>
                        <input type="text" class="form-control" id="judul" name="judul" placeholder="Judul Pengumuman" value="{{ old('judul') }}">
                        @if ($errors->has('judul'))
                        <small class="text-danger">{{ $errors->first('judul') }}</small>@endif
                    </div>
                    
                    <div class="form-group">
                        <label for="deskripsi">Deskripsi</label>
                        <textarea class="form-control" id="deskripsi" rows="20" name="deskripsi">{{ old('deskripsi')}}</textarea>
                        @if ($errors->has('deskripsi'))
                        <small class="text-danger">{{ $errors->first('deskripsi') }}</small>@endif
                    </div>
                    <button type="submit" class="btn btn-success mr-2">Submit</button>
                    <a href="{{ route('announcement.index') }}"><button class="btn btn-light">Cancel</button></a>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/announcement/formEdit.blade.php
@extends('layouts.admin')

@section('title')
    Update Pengumuman
@endsection

@section('content')
<div class="content-wrapper">
    <div class="row">
        <div class="col-md-12">
                @if ($message = Session::get('success'))
                <div class="flash-message">
                    <p class="alert alert-success">{{ $message }}  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
                </div>
                @endif
                @if ($message = Session::get('error'))
                <div class="flash-message">
                    <p class="alert alert-danger">{{ $message }}  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
                </div>
                @endif
        </div>
            
        <div class="col-md-12 grid-margin stretch-card">
                
            <div class="card">
                <div class="card-body">
                <h4 class="card-title">Pengumuman | Update Pengumuman</h4>
                <form class="forms-sample" action="{{ route('announcement.update', $announ->id) }}" method="post">
                    @method('PATCH') 
                    @csrf
                    <div class="form-group">
                        <label for="judul">Judul</label>
                        <input type="text" class="form-control" id="judul" name="judul" placeholder="Judul Info" value="{{ $announ->judul }}">
                        @if ($errors->has('judul'))
                        <small class="text-danger">{{ $errors->first('judul') }}</small>@endif
                    </div>
                    <div class="form-group">
                        <label for="deskripsi">Deskripsi</label>
                        <textarea class="form-control" id="deskripsi" rows="20" name="deskripsi">{{ $announ->deskripsi }}</textarea>
                        @if ($errors->has('deskripsi'))
                        <small class="text-danger">{{ $errors->first('deskripsi') }}</small>@endif
                    </div>
                    <button type="submit" class="btn btn-success mr-2">Submit</button>
                    <a href="{{ route('announcement.index') }}"><button class="btn btn-light">Cancel</button></a>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/announcement/index.blade.php
@extends('layouts.admin')

@section('title')
    Pengumuman 
@endsection

@section('content')
<div class="content-wrapper">
    <div class="row">
        <div class="col-md-12">
            @if ($message = Session::get('success'))
            <div class="flash-message">
                <p class="alert alert-success">{{ $message }}  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
            </div>
            @endif
      </div>
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <div class="row">
                <div class="col-lg-10"><h4 class="card-title">Pengumuman</h4></div>
                <div class="col-lg-2" align="right">
                    <a title="Tambah Berita | Info Terbaru" href="{{ route('announcement.create')}}">
                            <button type="button" class="btn btn-primary btn-fw" style="margin-right: 13px">
                                    <i class="mdi mdi-plus"></i>Tambah</button>
                    </a>
                </div>
                </div>
                <div class="table-responsive">
                  <table class="table table-striped" id="datatable-news">
                    <thead>
                      <tr>
                        <th>No</th>
                        <th>Tanggal</th>
                        <th>Judul</th>
                        <th>Aksi</th>
                      </tr>
                    </thead>
                    <tbody>
                       <?php $no = 1; ?>
                       @if(count($announ) > 0)
                       @foreach ($announ as $a)
                       <tr>
                            <td>{{ $no++ }}</td>
                            <td>{{ $a->created_at }}</td>
                            <td>{{ $a->judul }}</td>
                            <td><div class="btn-group" role="group" aria-label="Basic example">
                                  <button type="button" title="Ubah" class="btn btn-dark btn-sm"><a href="{{ route('announcement.edit', $a->id) }}" style="color: white"><i class="mdi mdi-pencil"></i></a></button>
                                  <form action="{{ route('announcement.destroy', $a->id) }}" method="POST">
                                  @csrf
                                  @method('DELETE')
                                  <button type="submit" title="Hapus" class="btn btn-danger btn-sm"><i class="mdi mdi-delete"></i></button>
                                  </form>
                                </div>
                            </td>
                        </tr>
                       @endforeach 
                       @else
                      <tr class="bg-secondary">
                        <td colspan="4" align="center">-- Tidak Ada Data --</td>
                      </tr>
                       @endif
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
    </div>
</div>

@endsection

resources/views/announcement/showAll.blade.php
@extends('layouts.frontend')

@section('title')
    Pengumuman
@endsection

@section('content')
<div class="container">
    <br>
        <div class="section">
            <div class="row">
                <div class="section health-section col-lg-9">
                    <h1 class="section-title">Pengumuman</h1>
                        @foreach($announcement as $ann)
                        <div class="health-feature">
                            <div class="post">
                                <div class="entry-header">
                                    <div class="entry-thumbnail">
                                        <img class="img-fluid" src="{{ asset('asset_general/images/announcements.png') }}" alt="" />
                                    </div>
                                </div>
                                <div class="post-content">								
                                    <div class="entry-meta">
                                        <ul class="list-inline">
                                            <li class="publish-date"><i class="fa fa-clock-o"></i> {{ $ann->created_at }} </li>
                                        </ul>
                                    </div>
                                    <h2 class="entry-title">
                                        <a href="{{ route('announcement.showById', $ann->id) }}">{{ $ann->judul }}</a>
                                    </h2>
                                </div>
                            </div><!--/post--> 
                        </div>
                        @endforeach
                        <div class="pagination-wrapper">
                        @if ($announcement->hasPages())
                        <ul class="pagination">
                            @if ($announcement->onFirstPage())
                                <li class="disabled" aria-disabled="true" aria-label="@lang('pagination.previous')">
                                    <span aria-hidden="true">&lsaquo;</span>
                                </li>
                            @else
                                <li ><a href="{{ $announcement->previousPageUrl() }}" rel="prev" aria-label="@lang('pagination.previous')"><span aria-hidden="true"><i class="fa fa-long-arrow-left"></i> Previous Page</span></a></li>
                            @endif
    
                            @foreach ($announcement as $ann)
                                @if (is_string($ann))
                                    <li class="disabled" aria-disabled="true"><span>{{ $element }}</span></li>
                                @endif
    
                                @if (is_array($ann))
                                    @foreach ($ann as $page => $url)
                                        @if ($page == $announcement->currentPage())
                                            <li class="active" aria-current="page"><span>{{ $page }}</span></li>
                                        @else
                                            <li><a href="{{ $url }}">{{ $page }}</a></li>
                                        @endif
                                    @endforeach
                                @endif
                            @endforeach
                            
                            @if ($announcement->hasMorePages())
                                <li><a href="{{ $announcement->nextPageUrl() }}" rel="next" aria-label="@lang('pagination.next')"><span aria-hidden="true">Next Page <i class="fa fa-long-arrow-right"></i></span></a></li>
                            @else
                                <li class="disabled" aria-disabled="true" aria-label="@lang('pagination.next')">
                                    <span aria-hidden="true">&rsaquo;</span>
                                </li>
                            @endif
                        </ul>
                        @endif
                    </div>
                </div><!--/#content--> 
            
            @include('layouts.frontend_sidebar')
        </div>				
    </div><!--/.section-->
    </div><!--/.container-->
@endsection

resources/views/announcement/showById.blade.php
@extends('layouts.frontend')

@section('title')
    Pengumuman
@endsection

@section('spasi')
    <br>
@endsection

@section('content')
<div class="container">
    <div class="section">
            <div class="row">
                <div class="col-md-8 col-lg-9">
                    <div id="site-content" class="site-content">
                        <div class="row">
                            <div class="col">
                                <div class="left-content">
                                    <div class="details-news">											
                                        <div class="post">
                                            <div class="entry-header">
                                                <div class="post-content">
                                                    <h2 class="entry-title">
                                                        {{ $ann->judul }}
                                                    </h2>
                                                    <div class="entry-meta">
                                                        <ul class="list-inline">
                                                            <li class="posted-by"><i class="fa fa-user"></i> by {{ $ann->admin_id }}</li>
                                                            <li class="publish-date"><i class="fa fa-clock-o"></i> {{ $ann->created_at }} </li>
                                                        </ul>
                                                    </div>
                                                    <hr>
                                                </div>
                                            </div>
                                            <div class="post-content" style="margin-top: -50px">								
                                                <div class="entry-content">
                                                    <p>{!! nl2br(e($ann->deskripsi)) !!}</p>

                                                    <ul class="list-inline share-link">
                                                        <li><a href="news-details.html#"><img src="https://demo.themeregion.com/newspress/images/others/s1.png" alt="" /></a></li>
                                                        <li><a href="news-details.html#"><img src="https://demo.themeregion.com/newspress/images/others/s2.png" alt="" /></a></li>
                                                        <li><a href="news-details.html#"><img src="https://demo.themeregion.com/newspress/images/others/s3.png" alt="" /></a></li>
                                                        <li><a href="news-details.html#"><img src="https://demo.themeregion.com/newspress/images/others/s4.png" alt="" /></a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div><!--/post--> 
                                    </div><!--/.section-->
                                </div><!--/.left-content-->
                            </div>
                        </div>
                    </div><!--/#site-content-->
                    
                </div><!--/.col-sm-9 -->	
                
                @include('layouts.frontend_sidebar')

            </div>				
        </div><!--/.section-->
    </div><!--/.container-->
@endsection