routes/web.php
<?php
use App\SubDistrict;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProfileController;

Route::get('/', 'WelcomeController@index')->name('/');

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
Route::group(['middleware' => ['web','auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
});

Route::get('/home', function(){
    if(Auth::user()->admin == 0)
    {
        return redirect()->action('WelcomeController@index');
    } 
    else 
    {
        return view('admin');
    }
})->name('home');

/* Announcement/Pengumuman */
Route::group(['prefix' => 'announcement'], function(){
    Route::get('/showAll', 'AnnouncementController@showAll')->name('announcement.showAll');
    Route::get('/showById/{id}', 'AnnouncementController@showById')->name('announcement.showById');
});
Route::resource('announcement', 'AnnouncementController');

/* Profile */
Route::group(['prefix' => 'profile'], function () {
    Route::get('/pkh', 'ProfileController@showPkh')->name('profile.pkh');
    Route::get('/visimisi', 'ProfileController@showVisiMisi')->name('profile.visimisi');
    Route::get('/tugasfungsi', 'ProfileController@showTugasFungsi')->name('profile.tugasfungsi'); 
    Route::get('/createNew/{jenis}', 'ProfileController@createNew')->name('profile.createNew');
});

Route::resource('profile', 'ProfileController');

/* Human Resource/SDM */
Route::resource('humanresource', 'HumanResourceController');
Route::get('/humanresource/detail/{id}', 'HumanResourceController@detail')->name('humanresource.detail');

/* Sub District/Kecamatan */
Route::resource('subdistrict', 'SubDistrictController');

/* Activity/Kegiatan */
Route::resource('activity', 'ActivityController');
Route::get('/activity/showById/{id}', 'ActivityController@showById')->name('activity.showById');
Route::patch('activity/updateStatus/{id}', 'ActivityController@updateStatus')->name('activity.updateStatus');

/* Comment/Komentar Kegiatan */
Route::resource('activitycomment', 'ActivityCommentController');

/* News/Berita */


Route::group(['prefix' => 'news'], function () {
    Route::get('/showAll', 'NewsController@showAll')->name('news.showAll');
    Route::get('/showById/{id}', 'NewsController@showById')->name('news.showById');
    Route::patch('/updateStatus/{id}', 'NewsController@updateStatus')->name('news.updateStatus');
});
Route::resource('news', 'NewsController');
Route::post('news/storeCategory', 'NewsController@storeCategory')->name('news.storeCategory');

/* Category/Kategori */
Route::patch('/category/storeNew', 'CategoryController@storeNew')->name('category.storeNew');
Route::resource('category', 'CategoryController');

/* Comment/Komentar Berita */
Route::resource('newscomment', 'NewsCommentController');

/* Product/Pemberdayaan Ekonomi (Produk) */
Route::get('/product/showAll', 'ProductController@showAll')->name('product.showAll');
Route::resource('product', 'ProductController');

/* Complaint/Sistem Pengaduan */
Route::group(['prefix' => 'complaint'], function () {
    Route::get('/formComplaint', 'ComplaintController@form')->name('complaint.formComplaint');
    Route::get('/getVillage/{id}', 'ComplaintController@getVillage')->name('complaint.getVillage');
});
Route::resource('complaint', 'ComplaintController');

/* Kontak/Contact */
Route::get('/contact/map', 'ContactController@showMap')->name('contact.map');
Route::resource('contact', 'ContactController');

/* Employee/Karyawan */
// Route::group(['prefix' => 'employee'], function () {
//     Route::get('/listByDistrict', 'EmployeeController@listByDistrict')->name('employee.listByDistrict');
//     Route::get('/detail/{id}', 'EmployeeController@detail')->name('employee.detail'); 
// });
Route::get('/employee/detail/{id}', 'EmployeeController@detail')->name('employee.detail');
Route::get('/employee/createNew/{id}', 'EmployeeController@createNew')->name('employee.createNew');
Route::get('/employee/getVillage/{id}', 'EmployeeController@getVillage')->name('employee.getVillage');
Route::resource('employee', 'EmployeeController');

/* Video */
Route::resource('video', 'VideoController');

/* Village */
Route::get('/village/createNew/{id}', 'VillageController@createNew')->name('village.createNew');
Route::resource('village', 'VillageController');

/* KPM atau PESERTA PKH */
Route::group(['prefix' => 'participant'], function () {
    Route::get('/showDataTahapI', 'ParticipantController@showDataTahapI')->name('participant.showDataTahapI');
    Route::get('/getVillage/{id}', 'ParticipantController@getVillage')->name('participant.getVillage');
});
Route::resource('participant', 'ParticipantController');

/* Download */
Route::get('/download/showDownload', 'DownloadController@showDownload')->name('download.showDownload');
Route::resource('download', 'DownloadController');
Route::get('/download/{uuid}/download', 'DownloadController@download')->name('download.download');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable =
    [
        'nama_produk','harga','jual_per','foto','deskripsi'
    ];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use App\Contact;
use DataTables;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::orderBy('created_at', 'desc')->paginate('20');

        return view('product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product.formCreate');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required|string|max:255|unique:products,nama_produk',
            'harga' => 'required',
            'satuan' => 'required',
            'image' => 'required|image|mimes:jpeg,png,jpg|max:2048'
        ]);
        $file       = Request()->file('image');
        $fileName   = $file->getClientOriginalName();
        Request()->file('image')->move(public_path('asset_general/images/product'), $fileName);
        $harga = explode(".",explode(" ",$request->get('harga'))[1]);
        $product = new Product([
            'nama_produk' => $request->get('nama'),
            'harga' => (int)implode($harga),
            'jual_per' => $request->get('satuan'),
            'foto' => $fileName,
            'deskripsi' => $request->get('deskripsi')
        ]);
        $product->save();
        return back()->with('success','Produk Baru berhasil ditambahkan !');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::where('id', $id)->first();
        return view('product.formEdit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama' => 'required|string|max:255',
            'harga' => 'required',
            'satuan' => 'required'
        ]);

        $product = Product::find($id);
        $product->nama_produk = $request->get('nama');
        $product->harga = $request->get('harga');
        $product->jual_per = $request->get('satuan');
        $product->deskripsi = $request->get('deskripsi');


        $file       = Request()->file('image');

        if($file) {
            $fileName   = $file->getClientOriginalName();
            Request()->file('image')->move(public_path('asset_general/images/product'), $fileName);
            $product->foto = $fileName;
        }

        try {
            $product->save();
            return redirect()->route('product.index')->with('success','Produk berhasil diupdate !');
        }
        catch (\Exception $e) {
            return back()->with('error','Produk gagal diupdate !');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::destroy($id);
        return back()->with('success', 'Produk berhasil dihapus!');
    }

    public function showAll()
    {
        // Ambil Semua Data Produk
        $products = Product::where('status', 'sale')->paginate('20');
        $contact  = Contact::All()->first();

        return view('product.showAll', compact(['products','contact']));
    }
}

resources/views/product/formCreate.blade.php
@extends('layouts.admin')

@section('title')
    Post Produk Baru
@endsection

@section('content')
<div class="content-wrapper">
    <div class="row">
        <div class="col-md-12">
                @if ($message = Session::get('success'))
                <div class="flash-message">
                    <p class="alert alert-success">{{ $message }}  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
                </div>
                @endif
        </div>
            
        <div class="col-md-12 grid-margin stretch-card">
                
            <div class="card">
                <div class="card-body">
                <h4 class="card-title">Pemberdayaan Ekonomi | Post Produk Baru</h4>
                <form class="forms-sample" action="{{ route('product.store') }}" method="POST" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <div class="row">
                    <div class="col-md-6">
                    <div class="form-group">
                        <label for="nama">Nama Produk</label>
                        <input type="text" class="form-control" id="nama" name="nama" placeholder="Nama Produk" value="{{ old('nama') }}">
                        @if ($errors->has('nama'))
                        <small class="text-danger">{{ $errors->first('nama') }}</small>@endif
                    </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Gambar/Foto</label>
                            <div class="input-group col-xs-12">
                                <input type="file" name="image" id="profile-img" class="form-control file-upload-info" placeholder="Gambar/Foto Produk" value="{{ old('image') }}">
                            </div>
                            @if ($errors->has('image'))
                            <small class="text-danger">{{ $errors->first('image') }}</small>@endif
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label>Preview</label><br>
                            <img src="{{ asset('asset_general/images/news/preview.png') }}" id="profile-img-tag" width="100px" height="100px" />
                        </div>
                    </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="satuan">Satuan Jual</label>
                                <select name="satuan" id="satuan" placeholder="Satuan Produk" class="form-control">
                                    <option value="">-- Silahkan Pilih --</option>
                                    <option value="pcs">Pcs</option>
                                    <option value="kg">Kg</option>
                                </select>
                                @if ($errors->has('satuan'))
                                <small class="text-danger">{{ $errors->first('satuan') }}</small>@endif
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="harga" class="harga">Harga</label>
                                <div class="input-group">
                                    <input type="text" name="harga" id="harga" class="form-control " placeholder="Harga Produk" value="{{ old('harga') }}" onkeypress="return hanyaAngka(event)">
                                </div>
                                @if ($errors->has('harga'))
                                <small class="text-danger">{{ $errors->first('harga') }}</small>@endif
                            </div>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="deskripsi">Deskripsi</label>
                        <textarea class="form-control" id="deskripsi" rows="10" name="deskripsi">{{ old('deskripsi')}}</textarea>
                        @if ($errors->has('deskripsi'))
                        <small class="text-danger">{{ $errors->first('deskripsi') }}</small>@endif
                    </div>
                    <button type="submit" class="btn btn-success mr-2">Submit</button>
                    <a href="{{ route('product.index') }}"><button class="btn btn-light">Cancel</button></a>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')
<script type="text/javascript">

jQuery(document).ready(function()
    {
        jQuery('select[name="satuan"]').on('change', function(){
            var satuan = jQuery(this).val();
            $('.harga').html('Harga /'+satuan);
        });
    });


    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#profile-img-tag').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#profile-img").change(function(){
        readURL(this);
    });

</script>

<script type="text/javascript">
		
    var rupiah = document.getElementById('harga');
    rupiah.addEventListener('keyup', function(e){
        // tambahkan 'Rp.' pada saat form di ketik
        // gunakan fungsi formatRupiah() untuk mengubah angka yang di ketik menjadi format angka
        rupiah.value = formatRupiah(this.value, 'Rp. ');
    });

    /* Fungsi formatRupiah */
    function formatRupiah(angka, prefix){
        var number_string = angka.replace(/[^,\d]/g, '').toString(),
        split   		= number_string.split(','),
        sisa     		= split[0].length % 3,
        rupiah     		= split[0].substr(0, sisa),
        ribuan     		= split[0].substr(sisa).match(/\d{3}/gi);

        // tambahkan titik jika yang di input sudah menjadi angka ribuan
        if(ribuan){
            separator = sisa ? '.' : '';
            rupiah += separator + ribuan.join('.');
        }

        rupiah = split[1] != undefined ? rupiah + ',' + split[1] : rupiah;
        return prefix == undefined ? rupiah : (rupiah ? 'Rp. ' + rupiah : '');
    }
</script>

<script>
        function hanyaAngka(evt) {
          var charCode = (evt.which) ? evt.which : event.keyCode
           if (charCode > 31 && (charCode < 48 || charCode > 57))
    
            return false;
          return true;
        }
    </script>


@endpush

resources/views/product/formEdit.blade.php
@extends('layouts.admin')

@section('title')
    Update Produk
@endsection

@section('content')
<div class="content-wrapper">
    <div class="row">
        <div class="col-md-12">
                @if ($message = Session::get('success'))
                <div class="flash-message">
                    <p class="alert alert-success">{{ $message }}  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
                </div>
                @endif
        </div>
            
        <div class="col-md-12 grid-margin stretch-card">
                
            <div class="card">
                <div class="card-body">
                <h4 class="card-title">Pemberdayaan Ekonomi | Update Produk</h4>
                <form class="forms-sample" action="{{ route('product.update', $product->id) }}" method="POST" enctype="multipart/form-data">
                    @method('PATCH') 
                    {{ csrf_field() }}
                    <div class="row">
                    <div class="col-md-6">
                    <div class="form-group">
                        <label for="nama">Nama Produk</label>
                        <input type="text" class="form-control" id="nama" name="nama" placeholder="Nama Produk" value="{{ $product->nama_produk }}">
                        @if ($errors->has('nama'))
                        <small class="text-danger">{{ $errors->first('nama') }}</small>@endif
                    </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Gambar/Foto</label>
                            <div class="input-group col-xs-12">
                                <input type="file" name="image" id="profile-img" class="form-control file-upload-info" placeholder="Gambar/Foto Produk">
                            </div>
                            @if ($errors->has('image'))
                            <small class="text-danger">{{ $errors->first('image') }}</small>@endif
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label>Preview</label><br>
                            <img src="{{ asset('asset_general/images/product/'.$product->foto.'') }}" id="profile-img-tag" width="100px" height="100px" />
                        </div>
                    </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="satuan">Satuan Jual</label>
                                <select name="satuan" id="satuan" placeholder="Satuan Produk" class="form-control">
                                    <option value="">-- Silahkan Pilih --</option>
                                    <option value="pcs" {{ $product->jual_per == 'pcs' ? 'selected' : '' }}>Pcs</option>
                                    <option value="kg" {{ $product->jual_per == 'kg' ? 'selected' : '' }}>Kg</option>
                                </select>
                                @if ($errors->has('satuan'))
                                <small class="text-danger">{{ $errors->first('satuan') }}</small>@endif
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="harga" class="harga">Harga</label>
                                <div class="input-group">
                                    <input type="text" name="harga" id="harga" class="form-control " placeholder="Harga Produk" value="{{ $product->harga }}" onkeypress="return hanyaAngka(event)">
                                </div>
                                @if ($errors->has('harga'))
                                <small class="text-danger">{{ $errors->first('harga') }}</small>@endif
                            </div>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="deskripsi">Deskripsi</label>
                        <textarea class="form-control" id="deskripsi" rows="10" name="deskripsi">{{ $product->deskripsi }}</textarea>
                        @if ($errors->has('deskripsi'))
                        <small class="text-danger">{{ $errors->first('deskripsi') }}</small>@endif
                    </div>
                    <button type="submit" class="btn btn-success mr-2">Submit</button>
                    <a href="{{ route('product.index') }}"><button class="btn btn-light">Cancel</button></a>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')
<script type="text/javascript">

jQuery(document).ready(function()
    {
        jQuery('select[name="satuan"]').on('change', function(){
            var satuan = jQuery(this).val();
            $('.harga').html('Harga /'+satuan);
        });
    });


    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#profile-img-tag').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#profile-img").change(function(){
        readURL(this);
    });
</script>

<script type="text/javascript">
		
    var rupiah = document.getElementById('harga');
    rupiah.addEventListener('keyup', function(e){
        // tambahkan 'Rp.' pada saat form di ketik
        // gunakan fungsi formatRupiah() untuk mengubah angka yang di ketik menjadi format angka
        rupiah.value = formatRupiah(this.value, 'Rp. ');
    });

    /* Fungsi formatRupiah */
    function formatRupiah(angka, prefix){
        var number_string = angka.replace(/[^,\d]/g, '').toString(),
        split   		= number_string.split(','),
        sisa     		= split[0].length % 3,
        rupiah     		= split[0].substr(0, sisa),
        ribuan     		= split[0].substr(sisa).match(/\d{3}/gi);

        // tambahkan titik jika yang di input sudah menjadi angka ribuan
        if(ribuan){
            separator = sisa ? '.' : '';
            rupiah += separator + ribuan.join('.');
        }

        rupiah = split[1] != undefined ? rupiah + ',' + split[1] : rupiah;
        return prefix == undefined ? rupiah : (rupiah ? 'Rp. ' + rupiah : '');
    }
</script>

<script>
    function hanyaAngka(evt) {
        var charCode = (evt.which) ? evt.which : event.keyCode
        if (charCode > 31 && (charCode < 48 || charCode > 57))

        return false;
        return true;
    }
</script>

@endpush

resources/views/product/index.blade.php
@extends('layouts.admin')

@section('title')
    Produk Ekonomi
@endsection

@section('content')
<div class="content-wrapper">
    <div class="row">
        <div class="col-md-12">
            @if ($message = Session::get('success'))
            <div class="flash-message">
                <p class="alert alert-success">{{ $message }}  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
            </div>
            @endif
      </div>
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <div class="row">
                <div class="col-lg-8"><h4 class="card-title">Produk Ekonomi</h4></div>
                <div class="col-lg-4" align="right">
                    <a href="{{ route('product.create')}}">
                        <button type="button" class="btn btn-primary btn-fw">
                        <i class="mdi mdi-plus"></i>Tambah</button>
                    </a>
                </div>
                </div>
                <div class="table-responsive">
                  <table class="table table-striped" id="datatable-product">
                    <thead>
                      <tr>
                        <th>No</th>
                        <th>Gambar</th>
                        <th>Nama Produk</th>
                        <th>Harga</th>
                        <th>Status</th>
                        <th>Aksi</th>
                      </tr>
                    </thead>
                    <tbody>
                       <?php $no = 1; ?>
                       @if(count($products) > 0)
                       @foreach ($products as $pro)
                       <tr>
                            <td>{{ $no++ }}</td>
                            <td class="py-1">
                                <img src="{{ asset('asset_general/images/product/'.$pro->foto.'') }}" alt="image" />
                            </td>
                            <td>{{ $pro->nama_produk }}</td>
                            <td>Rp {{ $pro->harga }} /{{ $pro->jual_per }}</td>
                            <td><select class="form-control">
                                    <option value="published">{{ $pro->status }}</option>
                                    @if($pro->status == 'sale')
                                        <option value="gudang">Gudang-kan</option>
                                    @else 
                                        <option value="sale">Jual</option>
                                    @endif
                                </select>
                            </td>
                            <td><div class="btn-group" role="group" aria-label="Basic example">
                                <button type="button" title="Ubah" class="btn btn-dark btn-sm"><a href="{{ route('product.edit', $pro->id) }}" style="color: white"><i class="mdi mdi-pencil"></i></a></button>
                                <form action="{{ route('product.destroy', $pro->id) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button type="submit" title="Hapus" class="btn btn-danger btn-sm"><i class="mdi mdi-delete"></i></button>
                                </form>
                              </div>
                          </td>
                        </tr>
                       @endforeach 
                       @else
                        <tr class="bg-secondary">
                          <td colspan="6" align="center">-- Tidak Ada Data --</td>
                        </tr>
                       @endif
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
    </div>
</div>

@endsection