routes/web.php
<?php
use App\SubDistrict;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProfileController;

Route::get('/', 'WelcomeController@index')->name('/');

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
Route::group(['middleware' => ['web','auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
});

Route::get('/home', function(){
    if(Auth::user()->admin == 0)
    {
        return redirect()->action('WelcomeController@index');
    } 
    else 
    {
        return view('admin');
    }
})->name('home');

/* Announcement/Pengumuman */
Route::group(['prefix' => 'announcement'], function(){
    Route::get('/showAll', 'AnnouncementController@showAll')->name('announcement.showAll');
    Route::get('/showById/{id}', 'AnnouncementController@showById')->name('announcement.showById');
});
Route::resource('announcement', 'AnnouncementController');

/* Profile */
Route::group(['prefix' => 'profile'], function () {
    Route::get('/pkh', 'ProfileController@showPkh')->name('profile.pkh');
    Route::get('/visimisi', 'ProfileController@showVisiMisi')->name('profile.visimisi');
    Route::get('/tugasfungsi', 'ProfileController@showTugasFungsi')->name('profile.tugasfungsi'); 
    Route::get('/createNew/{jenis}', 'ProfileController@createNew')->name('profile.createNew');
});

Route::resource('profile', 'ProfileController');

/* Human Resource/SDM */
Route::resource('humanresource', 'HumanResourceController');
Route::get('/humanresource/detail/{id}', 'HumanResourceController@detail')->name('humanresource.detail');

/* Sub District/Kecamatan */
Route::resource('subdistrict', 'SubDistrictController');

/* Activity/Kegiatan */
Route::resource('activity', 'ActivityController');
Route::get('/activity/showById/{id}', 'ActivityController@showById')->name('activity.showById');
Route::patch('activity/updateStatus/{id}', 'ActivityController@updateStatus')->name('activity.updateStatus');

/* Comment/Komentar Kegiatan */
Route::resource('activitycomment', 'ActivityCommentController');

/* News/Berita */


Route::group(['prefix' => 'news'], function () {
    Route::get('/showAll', 'NewsController@showAll')->name('news.showAll');
    Route::get('/showById/{id}', 'NewsController@showById')->name('news.showById');
    Route::patch('/updateStatus/{id}', 'NewsController@updateStatus')->name('news.updateStatus');
});
Route::resource('news', 'NewsController');
Route::post('news/storeCategory', 'NewsController@storeCategory')->name('news.storeCategory');

/* Category/Kategori */
Route::patch('/category/storeNew', 'CategoryController@storeNew')->name('category.storeNew');
Route::resource('category', 'CategoryController');

/* Comment/Komentar Berita */
Route::resource('newscomment', 'NewsCommentController');

/* Product/Pemberdayaan Ekonomi (Produk) */
Route::get('/product/showAll', 'ProductController@showAll')->name('product.showAll');
Route::resource('product', 'ProductController');

/* Complaint/Sistem Pengaduan */
Route::group(['prefix' => 'complaint'], function () {
    Route::get('/formComplaint', 'ComplaintController@form')->name('complaint.formComplaint');
    Route::get('/getVillage/{id}', 'ComplaintController@getVillage')->name('complaint.getVillage');
});
Route::resource('complaint', 'ComplaintController');

/* Kontak/Contact */
Route::get('/contact/map', 'ContactController@showMap')->name('contact.map');
Route::resource('contact', 'ContactController');

/* Employee/Karyawan */
// Route::group(['prefix' => 'employee'], function () {
//     Route::get('/listByDistrict', 'EmployeeController@listByDistrict')->name('employee.listByDistrict');
//     Route::get('/detail/{id}', 'EmployeeController@detail')->name('employee.detail'); 
// });
Route::get('/employee/detail/{id}', 'EmployeeController@detail')->name('employee.detail');
Route::get('/employee/createNew/{id}', 'EmployeeController@createNew')->name('employee.createNew');
Route::get('/employee/getVillage/{id}', 'EmployeeController@getVillage')->name('employee.getVillage');
Route::resource('employee', 'EmployeeController');

/* Video */
Route::resource('video', 'VideoController');

/* Village */
Route::get('/village/createNew/{id}', 'VillageController@createNew')->name('village.createNew');
Route::resource('village', 'VillageController');

/* KPM atau PESERTA PKH */
Route::group(['prefix' => 'participant'], function () {
    Route::get('/showDataTahapI', 'ParticipantController@showDataTahapI')->name('participant.showDataTahapI');
    Route::get('/getVillage/{id}', 'ParticipantController@getVillage')->name('participant.getVillage');
});
Route::resource('participant', 'ParticipantController');

/* Download */
Route::get('/download/showDownload', 'DownloadController@showDownload')->name('download.showDownload');
Route::resource('download', 'DownloadController');
Route::get('/download/{uuid}/download', 'DownloadController@download')->name('download.download');

app/Activity.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\ActivityCategory;
use App\ActivityComment;
use Carbon;

class Activity extends Model
{
    protected $fillable =
    [
        'id_kategori','judul','tgl_kegiatan','lok_kegiatan','uraian','foto'
    ];

    public function getCreatedAtAttribute()
    {
        return \Carbon\Carbon::parse($this->attributes['created_at'])->format('d, M Y');
    }

    public function getUpdatedAtAttribute()
    {
        return \Carbon\Carbon::parse($this->attributes['updated_at'])->diffForHumans();
    }

    public function activityCategory()
    {
        return $this->belongsTo(ActivityCategory::class, 'id_kategori', 'id');
    }

    public function getComments()
    {
        return $this->hasMany(ActivityComment::class, 'id_kegiatan', 'id');
    }

}

app/Http/Controllers/ActivityController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use App\ActivityCategory;
use App\Activity;
use App\ActivityComment;
use App\Participant;

class ActivityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $activity = Activity::with(['activityCategory','getComments'])->get();
        $group = $activity->groupBy(function ($activity){
            return $activity->activityCategory->kat_kegiatan;
        });
        return view('activity.index', compact('group'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = new Activity();
        $kategori = ActivityCategory::All()->sortBy('kat_kegiatan', SORT_NATURAL | SORT_FLAG_CASE)->pluck('kat_kegiatan', 'id');
        return view('activity.formCreate', compact(['model', 'kategori']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'kategori' => 'required',
            'judul' => 'required|string|max:255|unique:news,judul',
            'tgl' => 'required',
            'lokasi' => 'required',
            'uraian' => 'required',
            'image' => 'required|image|mimes:jpeg,png,jpg|max:2048'
        ]);
        $file       = Request()->file('image');
        $fileName   = $file->getClientOriginalName();
        Request()->file('image')->move(public_path('asset_general/images/activity'), $fileName);

        $act = new Activity([
            'id_kategori' => $request->get('kategori'),
            'judul' => $request->get('judul'),
            'tgl_kegiatan' => $request->get('tgl'),
            'lok_kegiatan' => $request->get('lokasi'),
            'foto' => $fileName,
            'uraian' => $request->get('uraian'),
            'admin_id' => Auth::id()
        ]);
        $act->save();
        return back()->with('success','Kegiatan Baru berhasil ditambahkan !');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = ActivityCategory::find($id);
        $activities = Activity::where([
            ['status', 'published'],
            ['id_kategori', $id]
        ])->paginate(12);

        return view('activity.showByCategory', compact(['category','activities']));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $act = Activity::where('id', $id)->with('activityCategory')->first();
        $kategori = ActivityCategory::orderBy('id', 'asc')->get();
        return view('activity.formEdit', compact(['act','kategori']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'kategori' => 'required',
            'judul' => 'required|string|max:255',
            'tgl' => 'required',
            'lokasi' => 'required',
            'uraian' => 'required'
        ]);

        $act = Activity::find($id);
        $act->id_kategori = $request->get('kategori');
        $act->judul = $request->get('judul');
        $act->tgl_kegiatan = $request->get('tgl');
        $act->lok_kegiatan = $request->get('lokasi');
        $act->uraian = $request->get('uraian');
        $act->admin_id = Auth::id();

        $file = Request()->file('image');

        if($file) {
            $fileName   = $file->getClientOriginalName();
            Request()->file('image')->move(public_path('asset_general/images/activity'), $fileName);
            $act->foto = $fileName;
        }

        try {
            $act->save();
            return redirect()->route('activity.index')->with('success','Kegiatan berhasil diupdate !');
        }
        catch (\Exception $e) {
            return back()->with('error','Kegiatan gagal diupdate !');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Activity::destroy($id);
        return back()->with('success', 'Kegiatan berhasil dihapus!');
        return redirect()->back();
    }

    public function showById($id)
    {
        // Ambil Data Kegiatan
        $activity = Activity::find($id);
        $idCategory = $activity->id_kategori;
        $category = ActivityCategory::find($idCategory);

        // Komentar
        $comments = ActivityComment::where('id_kegiatan', $id)->get();
        $publish = $comments->where('moderasi', 'yes');
        return view('activity.showById', compact(['category','activity','comments','publish']));
    }

    public function updateStatus(Request $request, $id)
    {
        $act = Activity::find($id);
        $act->status = $request->get('status');

        try {
            $act->save();
            return redirect()->route('activity.index')->with('success','Status Kegiatan berhasil diupdate !');
        }
        catch (\Exception $e) {
            return back()->with('error','Status Kegiatan gagal diupdate !');
        }
    }


    public function getDataChart()
    {
        $dataTemp = ['sed'=>[]] ;
        $dataTemp['labels'] = Participant::select(DB::raw('year(created_at) as year'))->groupBy('year')->pluck('year');
        $tahap1 = [] ;
        $tahap2 = [] ;
        $tahap3 = [] ;
        $tahap4 = [] ;
        foreach($dataTemp['labels'] as $d)
        {
            $dataTemp['datashets'][] = Participant::select('tahap',DB::raw('year(created_at) as year'),DB::raw('concat("Tahap ",tahap) as labels'))->where(DB::raw('year(created_at)'),$d)->orderBy('tahap','ASC')->get();
            // $k1 = 0 ;
            // $k2 = 0 ;
            // $k3 = 0 ;
            // $k4 = 0 ;

        }


        return \response()->json($dataTemp);
    }



}

resources/views/activity/formCreate.blade.php
@extends('layouts.admin')

@section('title')
    Post Kegiatan Baru
@endsection

@section('content')
<div class="content-wrapper">
    <div class="row">
        <div class="col-md-12">
                @if ($message = Session::get('success'))
                <div class="flash-message">
                    <p class="alert alert-success">{{ $message }}  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
                </div>
                @endif
        </div>

        <div class="col-md-12 grid-margin stretch-card">

            <div class="card">
                <div class="card-body">
                <h4 class="card-title">Aktivitas | Post Kegiatan Baru</h4>
                <form class="forms-sample" action="{{ route('activity.store') }}" method="POST" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="judul">Judul</label>
                        <input type="text" class="form-control" id="judul" name="judul" placeholder="Judul Kegiatan" value="{{ old('judul') }}">
                        @if ($errors->has('judul'))
                        <small class="text-danger">{{ $errors->first('judul') }}</small>@endif
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="kategori">Kategori</label>
                                {!! Form::select('kategori', $kategori, null, ['class'=>'form-control', 'placeholder'=> '-- Kategori Kegiatan --', 'value' => '{{ old("kategori")}}']) !!}
                                @if ($errors->has('kategori'))
                                <small class="text-danger">{{ $errors->first('kategori') }}</small>@endif
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Gambar/Foto</label>
                                <div class="input-group col-xs-12">
                                    <input type="file" name="image" id="profile-img" class="form-control file-upload-info" placeholder="Gambar/Foto Kegiatan" value="{{ old('image') }}">
                                </div>
                                @if ($errors->has('image'))
                                <small class="text-danger">{{ $errors->first('image') }}</small>@endif
                            </div>
                        </div>
                        <div class="col-md-2">
                                <div class="form-group">
                                    <label>Preview</label><br>
                                    <img src="{{ asset('asset_general/images/news/preview.png') }}" id="profile-img-tag" width="100px" height="100px" />
                                </div>
                            </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="tgl">Tanggal</label>
                                <div class="input-group col-xs-12">
                                    <input type="date" name="tgl" id="tgl_kegiatan" class="form-control" placeholder="Tanggal Kegiatan" value="{{ old('tgl') }}">
                                </div>
                                @if ($errors->has('tgl'))
                                <small class="text-danger">{{ $errors->first('tgl') }}</small>@endif
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="lokasi">Lokasi</label>
                                <div class="input-group col-xs-12">
                                    <input type="text" name="lokasi" class="form-control" placeholder="Lokasi Kegiatan" value="{{ old('lokasi') }}">
                                </div>
                                @if ($errors->has('lokasi'))
                                <small class="text-danger">{{ $errors->first('lokasi') }}</small>@endif
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="uraian">Uraian</label>
                        <textarea class="form-control summernote-editor" id="uraian" rows="30" name="uraian">{{ old('uraian')}}</textarea>
                        @if ($errors->has('uraian'))
                        <small class="text-danger">{{ $errors->first('uraian') }}</small>@endif
                    </div>
                    <button type="submit" class="btn btn-success mr-2">Submit</button>
                    <a href="{{ route('activity.index') }}"><button class="btn btn-light">Cancel</button></a>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')
<script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#profile-img-tag').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#profile-img").change(function(){
        readURL(this);
    });
</script>
@endpush

resources/views/activity/formEdit.blade.php
@extends('layouts.admin')

@section('title')
    Update Kegiatan
@endsection

@section('content')
<div class="content-wrapper">
    <div class="row">
        <div class="col-md-12">
                @if ($message = Session::get('success'))
                <div class="flash-message">
                    <p class="alert alert-success">{{ $message }}  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
                </div>
                @endif
                @if ($message = Session::get('error'))
                <div class="flash-message">
                    <p class="alert alert-danger">{{ $message }}  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
                </div>
                @endif
        </div>

        <div class="col-md-12 grid-margin stretch-card">

            <div class="card">
                <div class="card-body">
                <h4 class="card-title">Aktivitas | Update Kegiatan</h4>
                <form class="forms-sample" action="{{ route('activity.update', $act->id) }}" method="post" enctype="multipart/form-data">
                    @method('PATCH')
                    @csrf
                    <div class="form-group">
                        <label for="judul">Judul</label>
                        <input type="text" class="form-control" id="judul" name="judul" placeholder="Judul Info" value="{{ $act->judul }}">
                        @if ($errors->has('judul'))
                        <small class="text-danger">{{ $errors->first('judul') }}</small>@endif
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="kategori">Kategori</label>
                                <select class="form-control" id="kategori" name="kategori">
                                    @if(count($kategori) > 0)
                                    @foreach($kategori as $kat)
                                        <option value="{{ $kat->id }}" {{ $kat->id == $act->activityCategory->id ? 'selected' : '' }}>{{ $kat->kat_kegiatan }}</option>
                                    @endforeach
                                    @else
                                    <option value="">-- Data Kategori Belum Tersedia --</option>
                                    @endif
                                </select>
                                @if ($errors->has('kategori'))
                                <small class="text-danger">{{ $errors->first('kategori') }}</small>@endif
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Gambar/Foto</label>
                                <div class="input-group col-xs-12">
                                    <input type="file" name="image" id="profile-img" class="form-control file-upload-info" placeholder="Gambar/Foto Info">
                                </div>
                                @if ($errors->has('image'))
                                <small class="text-danger">{{ $errors->first('image') }}</small>@endif
                            </div>
                        </div>
                        <div class="col-md-2">
                                <div class="form-group">
                                    <label>Preview</label><br>
                                    <img src="{{ asset('asset_general/images/activity/'.$act->foto.'') }}" id="profile-img-tag" width="150px" height="150px" />
                                </div>
                            </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="tgl">Tanggal</label>
                                <div class="input-group col-xs-12">
                                    <input type="text" name="tgl" id="tgl_kegiatan" class="form-control" placeholder="Tanggal Kegiatan" value="{{ $act->tgl_kegiatan }}">
                                </div>
                                @if ($errors->has('tgl'))
                                <small class="text-danger">{{ $errors->first('tgl') }}</small>@endif
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="lokasi">Lokasi</label>
                                <div class="input-group col-xs-12">
                                    <input type="text" name="lokasi" class="form-control" placeholder="Lokasi Kegiatan" value="{{ $act->lok_kegiatan }}">
                                </div>
                                @if ($errors->has('lokasi'))
                                <small class="text-danger">{{ $errors->first('lokasi') }}</small>@endif
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="uraian">Uraian</label>
                        <textarea class="form-control summernote-editor" id="uraian" rows="30" name="uraian">{{ $act->uraian }}</textarea>
                        @if ($errors->has('uraian'))
                        <small class="text-danger">{{ $errors->first('uraian') }}</small>@endif
                    </div>
                    <button type="submit" class="btn btn-success mr-2">Submit</button>
                    <a href="{{ route('activity.index') }}"><button class="btn btn-light">Cancel</button></a>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')
<script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#profile-img-tag').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#profile-img").change(function(){
        readURL(this);
    });
</script>
@endpush

resources/views/activity/index.blade.php
@extends('layouts.admin')

@section('title')
    Kegiatan 
@endsection

@section('content')
<div class="content-wrapper">
    <div class="row">
        <div class="col-md-12">
            @if ($message = Session::get('success'))
            <div class="flash-message">
                <p class="alert alert-success">{{ $message }}  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
            </div>
            @endif
      </div>
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <div class="row">
                <div class="col-lg-8"><h4 class="card-title font-weight-bold">Kegiatan</h4></div>
                <div class="col-lg-4" align="right">
                    <a href="{{ route('activity.create')}}">
                        <button type="button" class="btn btn-primary btn-fw">
                        <i class="mdi mdi-plus"></i>Tambah</button>
                    </a>
                </div>
                </div>
                <div class="table-responsive">
                  <table class="table table-striped">
                    <thead>
                      <tr>
                        <th>No</th>
                        <th>Judul</th>
                        <th>Lokasi & Tanggal Kegiatan</th>
                        <th>Status</th>
                        <th>#</th>
                        <th>Tanggal</th>
                        <th>Aksi</th>
                      </tr>
                    </thead>
                    <tbody> 
                      @if(count($group) > 0)
                       @foreach($group as $category => $activity)
                        <tr>
                          <td colspan="7" class="table-primary" align="center"><strong>{{ $category }}</strong></td>
                        </tr>
                       <?php $no = 1 ?>
                       @foreach ($activity as $act)
                       <tr>
                            <td>{{ $no++ }}</td>
                            <td>{{ $act->judul }}</td>
                            <td>{{ $act->lok_kegiatan }} | {{ date('d, F Y', strtotime($act->tgl_kegiatan)) }}</td>
                            <td><button type="button" class="btn btn-success dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ $act->status }}
                              </button>
                              @if($act->status == 'published')
                              <div class="dropdown-menu">
                                <form action="{{ route('activity.updateStatus', $act->id) }}" method="post">
                                  @method('PATCH')
                                @csrf
                                <input type="hidden" name="status" value="drafted">
                                <button type="submit"><a class="dropdown-item">
                                  <i class="mdi mdi-eye-off"></i> Draft-kan</a></button>
                                </form>
                              </div>
                              @else 
                              <div class="dropdown-menu">
                                  <form action="{{ route('activity.updateStatus', $act->id) }}" method="post">
                                    @method('PATCH')
                                  @csrf
                                  <input type="hidden" name="status" value="published">
                                  <button type="submit"><a class="dropdown-item">
                                    <i class="mdi mdi-send"></i> Publish</a></button>
                                  </form>
                                </div>
                               @endif
                            </td>
                            <td>
                                <i class="mdi mdi-comment-text-outline mx-0"></i> {{ count($act->getComments) }} 
                                <br><i class="mdi mdi-eye mx-0"></i> 1.5k
                            </td>
                            <td>{{ $act->created_at }}</td>
                            <td><div class="btn-group" role="group" aria-label="Basic example">
                                <button type="button" title="Ubah" class="btn btn-dark btn-sm"><a href="{{ route('activity.edit', $act->id) }}" style="color: white"><i class="mdi mdi-pencil"></i></a></button>
                                <form action="{{ route('activity.destroy', $act->id) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button type="submit" title="Hapus" class="btn btn-danger btn-sm"><i class="mdi mdi-delete"></i></button>
                                </form>
                              </div>
                            </td>
                        </tr>
                       @endforeach 
                       @endforeach
                       @else
                        <tr class="bg-secondary">
                          <td colspan="7" align="center">-- Tidak Ada Data --</td>
                        </tr>
                       @endif
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
    </div>
</div>

@endsection