routes/web.php
<?php
use App\SubDistrict;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProfileController;

Route::get('/', 'WelcomeController@index')->name('/');

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
Route::group(['middleware' => ['web','auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
});

Route::get('/home', function(){
    if(Auth::user()->admin == 0)
    {
        return redirect()->action('WelcomeController@index');
    } 
    else 
    {
        return view('admin');
    }
})->name('home');

/* Announcement/Pengumuman */
Route::group(['prefix' => 'announcement'], function(){
    Route::get('/showAll', 'AnnouncementController@showAll')->name('announcement.showAll');
    Route::get('/showById/{id}', 'AnnouncementController@showById')->name('announcement.showById');
});
Route::resource('announcement', 'AnnouncementController');

/* Profile */
Route::group(['prefix' => 'profile'], function () {
    Route::get('/pkh', 'ProfileController@showPkh')->name('profile.pkh');
    Route::get('/visimisi', 'ProfileController@showVisiMisi')->name('profile.visimisi');
    Route::get('/tugasfungsi', 'ProfileController@showTugasFungsi')->name('profile.tugasfungsi'); 
    Route::get('/createNew/{jenis}', 'ProfileController@createNew')->name('profile.createNew');
});

Route::resource('profile', 'ProfileController');

/* Human Resource/SDM */
Route::resource('humanresource', 'HumanResourceController');
Route::get('/humanresource/detail/{id}', 'HumanResourceController@detail')->name('humanresource.detail');

/* Sub District/Kecamatan */
Route::resource('subdistrict', 'SubDistrictController');

/* Activity/Kegiatan */
Route::resource('activity', 'ActivityController');
Route::get('/activity/showById/{id}', 'ActivityController@showById')->name('activity.showById');
Route::patch('activity/updateStatus/{id}', 'ActivityController@updateStatus')->name('activity.updateStatus');

/* Comment/Komentar Kegiatan */
Route::resource('activitycomment', 'ActivityCommentController');

/* News/Berita */


Route::group(['prefix' => 'news'], function () {
    Route::get('/showAll', 'NewsController@showAll')->name('news.showAll');
    Route::get('/showById/{id}', 'NewsController@showById')->name('news.showById');
    Route::patch('/updateStatus/{id}', 'NewsController@updateStatus')->name('news.updateStatus');
});
Route::resource('news', 'NewsController');
Route::post('news/storeCategory', 'NewsController@storeCategory')->name('news.storeCategory');

/* Category/Kategori */
Route::patch('/category/storeNew', 'CategoryController@storeNew')->name('category.storeNew');
Route::resource('category', 'CategoryController');

/* Comment/Komentar Berita */
Route::resource('newscomment', 'NewsCommentController');

/* Product/Pemberdayaan Ekonomi (Produk) */
Route::get('/product/showAll', 'ProductController@showAll')->name('product.showAll');
Route::resource('product', 'ProductController');

/* Complaint/Sistem Pengaduan */
Route::group(['prefix' => 'complaint'], function () {
    Route::get('/formComplaint', 'ComplaintController@form')->name('complaint.formComplaint');
    Route::get('/getVillage/{id}', 'ComplaintController@getVillage')->name('complaint.getVillage');
});
Route::resource('complaint', 'ComplaintController');

/* Kontak/Contact */
Route::get('/contact/map', 'ContactController@showMap')->name('contact.map');
Route::resource('contact', 'ContactController');

/* Employee/Karyawan */
// Route::group(['prefix' => 'employee'], function () {
//     Route::get('/listByDistrict', 'EmployeeController@listByDistrict')->name('employee.listByDistrict');
//     Route::get('/detail/{id}', 'EmployeeController@detail')->name('employee.detail'); 
// });
Route::get('/employee/detail/{id}', 'EmployeeController@detail')->name('employee.detail');
Route::get('/employee/createNew/{id}', 'EmployeeController@createNew')->name('employee.createNew');
Route::get('/employee/getVillage/{id}', 'EmployeeController@getVillage')->name('employee.getVillage');
Route::resource('employee', 'EmployeeController');

/* Video */
Route::resource('video', 'VideoController');

/* Village */
Route::get('/village/createNew/{id}', 'VillageController@createNew')->name('village.createNew');
Route::resource('village', 'VillageController');

/* KPM atau PESERTA PKH */
Route::group(['prefix' => 'participant'], function () {
    Route::get('/showDataTahapI', 'ParticipantController@showDataTahapI')->name('participant.showDataTahapI');
    Route::get('/getVillage/{id}', 'ParticipantController@getVillage')->name('participant.getVillage');
});
Route::resource('participant', 'ParticipantController');

/* Download */
Route::get('/download/showDownload', 'DownloadController@showDownload')->name('download.showDownload');
Route::resource('download', 'DownloadController');
Route::get('/download/{uuid}/download', 'DownloadController@download')->name('download.download');

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\NewsCategory;
use App\NewsComment;
use App\User;

class News extends Model
{
    protected $fillable =
    [
        'id_kategori','judul','uraian','image'
    ];

    public function getCreatedAtAttribute()
    {
        return \Carbon\Carbon::parse($this->attributes['created_at'])->format('d, M Y');
    }

    public function getUpdatedAtAttribute()
    {
        return \Carbon\Carbon::parse($this->attributes['created_at'])->diffForHumans();
    }

    public function newsCategory()
    {
        return $this->belongsTo(NewsCategory::class, 'id_kategori', 'id');
    }

    public function getComment()
    {
        return $this->hasMany(NewsComment::class, 'id_berita', 'id');
    }

    public function getAdmin()
    {
        return $this->belongsTo(User::class, 'id_admin', 'id');
    }

}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Validator,Redirect,Response;
use App\News;
use App\NewsCategory;
use App\NewsComment;
use App\Admin;
use DataTables;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $news = News::orderBy('created_at', 'desc')->with(['newsCategory','getComment'])->paginate(10);
        // $admin = Auth::guard('admin');

        // dd($admin);
        return view('news.index', compact('news'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kategori = NewsCategory::All()->sortBy('nama_kategori', SORT_NATURAL | SORT_FLAG_CASE)->pluck('nama_kategori', 'id');
        return view('news.formCreate', compact('kategori'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'kategori' => 'required',
            'judul' => 'required|string|max:255|unique:news,judul',
            'uraian' => 'required',
            'image' => 'required|image|mimes:jpeg,png,jpg|max:2048'
        ]);
        $file       = Request()->file('image');
        $fileName   = $file->getClientOriginalName();
        Request()->file('image')->move(public_path('asset_general/images/news'), $fileName);

        $news = new News([
            'id_kategori' => $request->get('kategori'),
            'judul' => $request->get('judul'),
            'image' => $fileName,
            'uraian' => $request->get('uraian'),
            'admin_id' => Auth::id()
        ]);
        $news->save();
        return back()->with('success','Info Baru berhasil ditambahkan !');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // $category = NewsCategory::find($id);
        // $news = $category->news()->paginate(10);

        // return view('news.showByCategory', compact(['category','news']));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $news = News::where('id', $id)->with('newsCategory')->first();
        $kategori = NewsCategory::orderBy('nama_kategori', 'asc')->get();
        return view('news.formEdit', compact(['news','kategori']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'kategori' => 'required',
            'judul' => 'required|string|max:255',
            'uraian' => 'required'
        ]);

        $news = News::find($id);
        $news->id_kategori = $request->get('kategori');
        $news->judul = $request->get('judul');
        $news->uraian = $request->get('uraian');
        $news->admin_id = Auth::id();

        $file       = Request()->file('image');

        if($file) {
            $fileName   = $file->getClientOriginalName();
            Request()->file('image')->move(public_path('asset_general/images/news'), $fileName);
            $news->image = $fileName;
        }

        try {
            $news->save();
            return redirect()->route('news.index')->with('success','Info berhasil diupdate !');
        }
        catch (\Exception $e) {
            return back()->with('error','Info gagal diupdate !');
        }
    }

    public function updateStatus(Request $request, $id)
    {
        $news = News::find($id);
        $news->status = $request->get('status');

        try {
            $news->save();
            return redirect()->route('news.index')->with('success','Status Info berhasil diupdate !');
        }
        catch (\Exception $e) {
            return back()->with('error','Status Info gagal diupdate !');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        News::destroy($id);
        return back()->with('success', 'Info berhasil dihapus!');
    }

    public function showById($id)
    {
        // Ambil Data Berita
        $news = News::find($id);
        $idCategory = $news->id_kategori;
        $category = NewsCategory::find($idCategory);

        // Komentar
        $comments = NewsComment::where('id_berita', $id)->get();
        $publish = $comments->where('moderasi', 'yes');
        return view('news.showById', compact(['category','news', 'comments','publish']));
    }

    public function showAll()
    {
        // Ambil Semua Data Berita
        $news = News::orderBy('created_at', 'desc')->where('status', 'published')->with(['newsCategory','getComment'])->paginate(12);

        return view('news.showAll', compact('news'));
    }

    public function storeCategory(Request $request)
    {
        Request()->validate([
            'kategori_new' => 'required'
        ]);

            $data = $request->all();
            $check = NewsCategory::insert($data);
            $arr = array('msg' => 'Something goes to wrong. Please try again lator', 'status' => false);
            if($check){
            $arr = array('msg' => 'Successfully submit form using ajax', 'status' => true);
            }
            return Response()->json($arr);
    }
}

resources/views/news/formCreate.blade.php
@extends('layouts.admin')

@section('title')
    Post Info Baru
@endsection

@section('content')
<div class="content-wrapper">
    <div class="row">
        <div class="col-md-12">
                @if ($message = Session::get('success'))
                <div class="flash-message">
                    <p class="alert alert-success">{{ $message }}  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
                </div>
                @endif
        </div>

        <div class="col-md-12 grid-margin stretch-card" id="myForm">
                
            <div class="card">
                <div class="card-body">
                    <form id="kategori-form" method="POST" action="javascript:void(0)">
                        @csrf
                    <div class="row">
                        <div class="col-md-4">
                        <div class="form-group">
                            <label for="kategori_new">Nama Kategori</label>
                            <input type="text" class="form-control" id="kategori_new" name="kategori_new" placeholder="Nama Kategori Baru">
                            @if ($errors->has('kategori_new'))
                            <small class="text-danger">{{ $errors->first('kategori_new') }}</small>@endif
                        </div>
                        </div>
                        <div class="col-md-8">
                        <div class="form-group">
                            <label for="deskripsi">Deskripsi</label>
                            <textarea class="form-control" id="deskripsi" name="deskripsi" rows="4"></textarea>
                        </div>
                        </div>
                        <div class="alert alert-success d-none" id="msg_div">
                            <span id="res_message"></span>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                            <button type="submit" class="btn btn-success mr-2 btn-save" id="send_form">Submit</button>
                            <button class="btn btn-light btn-slide">Cancel</button>
                            </div>
                        </div>
                    </div>
                </form>
                </div>
            </div>
        </div>
        
            
        <div class="col-md-12 grid-margin stretch-card">
                
            <div class="card">
                <div class="card-body">
                <h4 class="card-title">Berita | Post Info Baru</h4>
                <form class="forms-sample" action="{{ route('news.store') }}" method="POST" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="judul">Judul</label>
                        <input type="text" class="form-control" id="judul" name="judul" placeholder="Judul Info" value="{{ old('judul') }}">
                        @if ($errors->has('judul'))
                        <small class="text-danger">{{ $errors->first('judul') }}</small>@endif
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="kategori">Kategori</label>
                                {!! Form::select('kategori', $kategori, null, ['class'=>'form-control', 'placeholder'=> '-- Kategori Info --', 'value' => '{{ old("kategori")}}']) !!}
                                @if ($errors->has('kategori'))
                                <small class="text-danger">{{ $errors->first('kategori') }}</small>@endif
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <br>
                                <button type="button" class="btn btn-outline-primary btn-slide">
                                <i class="mdi mdi-plus"></i> Katgeori Baru</button>
                            </div>
                        </div>
                        
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Gambar/Foto</label>
                                <div class="input-group col-xs-12">
                                    <input type="file" name="image" id="profile-img" class="form-control file-upload-info" placeholder="Gambar/Foto Info" value="{{ old('image') }}">
                                </div>
                                @if ($errors->has('image'))
                                <small class="text-danger">{{ $errors->first('image') }}</small>@endif
                            </div>
                        </div>
                        <div class="col-md-2">
                                <div class="form-group">
                                    <label>Preview</label><br>
                                    <img src="{{ asset('asset_general/images/news/preview.png') }}" id="profile-img-tag" width="100px" height="100px" />
                                </div>
                            </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="uraian">Uraian</label>
                        <textarea class="form-control" id="uraian" rows="30" name="uraian">{{ old('uraian')}}</textarea>
                        @if ($errors->has('uraian'))
                        <small class="text-danger">{{ $errors->first('uraian') }}</small>@endif
                    </div>
                    <button type="submit" class="btn btn-success mr-2">Submit</button>
                    <a href="{{ route('news.index') }}"><button class="btn btn-light">Cancel</button></a>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')
<script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#profile-img-tag').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#profile-img").change(function(){
        readURL(this);
    });
</script>

<script>
$(document).ready(function() {
 
 $("#myForm").hide();

 $('.card').on("click", '.btn-slide', function() {
     $("#myForm").slideToggle("slow");
 });

});


if ($("#kategori-form").length > 0) {
         $("#kategori-form").validate({
           
         rules: {
           kategori_new: {
             required: true
           },  
         },
         messages: {
             
           kategori_new: {
             required: "Nama Kategori harus diisi !"
           },
              
         },
         submitHandler: function(form) {
          $.ajaxSetup({
               headers: {
                   'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
               }
           });
           $('#send_form').html('Sending..');
           $.ajax({
             url: '{{ route("category.storeNew") }}',
             type: "PUT",
             data: $('#kategori-form').serialize(),
             success: function(response) {
                 $('#send_form').html('Submit');
                 $('#res_message').show();
                 $('#res_message').html(response.msg);
                 $('#msg_div').removeClass('d-none');
      
                 document.getElementById("kategori-form").reset(); 
                 setTimeout(function(){
                 $('#res_message').hide();
                 $('#msg_div').hide();
                 },10000);
             }
           });
         }
       })
     }
        
</script>

@endpush

resources/views/news/formEdit.blade.php
@extends('layouts.admin')

@section('title')
    Update Info
@endsection

@section('content')
<div class="content-wrapper">
    <div class="row">
        <div class="col-md-12">
                @if ($message = Session::get('success'))
                <div class="flash-message">
                    <p class="alert alert-success">{{ $message }}  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
                </div>
                @endif
                @if ($message = Session::get('error'))
                <div class="flash-message">
                    <p class="alert alert-danger">{{ $message }}  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
                </div>
                @endif
        </div>
            
        <div class="col-md-12 grid-margin stretch-card">
                
            <div class="card">
                <div class="card-body">
                <h4 class="card-title">Berita | Update Info</h4>
                <form class="forms-sample" action="{{ route('news.update', $news->id) }}" method="post" enctype="multipart/form-data">
                    @method('PATCH') 
                    @csrf
                    <div class="form-group">
                        <label for="judul">Judul</label>
                        <input type="text" class="form-control" id="judul" name="judul" placeholder="Judul Info" value="{{ $news->judul }}">
                        @if ($errors->has('judul'))
                        <small class="text-danger">{{ $errors->first('judul') }}</small>@endif
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="kategori">Kategori</label>
                                <select class="form-control" id="kategori" name="kategori">
                                    @if(count($kategori) > 0)
                                    @foreach($kategori as $kat)
                                        <option value="{{ $kat->id }}" {{ $kat->id == $news->newsCategory->id ? 'selected' : '' }}>{{ $kat->nama_kategori }}</option>
                                    @endforeach
                                    @else
                                    <option value="">-- Data Kategori Belum Tersedia --</option>
                                    @endif
                                </select>
                                @if ($errors->has('kategori'))
                                <small class="text-danger">{{ $errors->first('kategori') }}</small>@endif
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Gambar/Foto</label>
                                <div class="input-group col-xs-12">
                                    <input type="file" name="image" id="profile-img" class="form-control file-upload-info" placeholder="Gambar/Foto Info">
                                </div>
                                @if ($errors->has('image'))
                                <small class="text-danger">{{ $errors->first('image') }}</small>@endif
                            </div>
                        </div>
                        <div class="col-md-2">
                                <div class="form-group">
                                    <label>Preview</label><br>
                                    <img src="{{ asset('asset_general/images/news/'.$news->image.'') }}" id="profile-img-tag" width="150px" height="150px" />
                                </div>
                            </div>
                    </div>
                    <div class="form-group">
                        <label for="uraian">Uraian</label>
                        <textarea class="form-control" id="uraian" rows="30" name="uraian">{{ $news->uraian }}</textarea>
                        @if ($errors->has('uraian'))
                        <small class="text-danger">{{ $errors->first('uraian') }}</small>@endif
                    </div>
                    <button type="submit" class="btn btn-success mr-2">Submit</button>
                    <a href="{{ route('news.index') }}"><button class="btn btn-light">Cancel</button></a>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')
<script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#profile-img-tag').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#profile-img").change(function(){
        readURL(this);
    });
</script>
@endpush

resources/views/news/index.blade.php
@extends('layouts.admin')

@section('title')
    Info Terbaru  
@endsection

@section('content')
<div class="content-wrapper">
    <div class="row">
        <div class="col-md-12">
            @if ($message = Session::get('success'))
            <div class="flash-message">
                <p class="alert alert-success">{{ $message }}  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
            </div>
            @endif
      </div>
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <div class="row">
                <div class="col-lg-10"><h4 class="card-title">Info Terbaru</h4></div>
                <div class="col-lg-2" align="right">
                    <a title="Tambah Berita | Info Terbaru" href="{{ route('news.create')}}">
                            <button type="button" class="btn btn-primary btn-fw" style="margin-right: 13px">
                                    <i class="mdi mdi-plus"></i>Tambah</button>
                    </a>
                </div>
                </div>
                <div class="table-responsive">
                  <table class="table table-striped" id="datatable-news">
                    <thead>
                      <tr>
                        <th>No</th>
                        <th>Tanggal</th>
                        <th>Judul</th>
                        <th>Kategori</th>
                        <th>Status</th>
                        <th>Aksi</th>
                      </tr>
                    </thead>
                    <tbody>
                       <?php $no = 1; ?>
                       @if(count($news) > 0)
                       @foreach ($news as $new)
                       <tr>
                            <input type="hidden" id="idNews" value="{{ $new->id }}">
                            <td>{{ $no++ }}</td>
                            <td>{{ $new->created_at }}</td>
                            <td>{{ $new->judul }}</td>
                            <td><button class="btn btn-outline-primary">{{ $new->newsCategory->nama_kategori }}</button></td>
                            <td><button type="button" class="btn btn-success dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ $new->status }}
                              </button>
                              @if($new->status == 'published')
                              <div class="dropdown-menu">
                                <form action="{{ route('news.updateStatus', $new->id) }}" method="post">
                                  @method('PATCH')
                                @csrf
                                <input type="hidden" name="status" value="drafted">
                                <button type="submit"><a class="dropdown-item">
                                  <i class="mdi mdi-eye-off"></i> Draft-kan</a></button>
                                </form>
                              </div>
                              @else 
                              <div class="dropdown-menu">
                                  <form action="{{ route('news.updateStatus', $new->id) }}" method="post">
                                    @method('PATCH')
                                  @csrf
                                  <input type="hidden" name="status" value="published">
                                  <button type="submit"><a class="dropdown-item">
                                    <i class="mdi mdi-send"></i> Publish</a></button>
                                  </form>
                                </div>
                               @endif
                            </td>
                            <td>
                                <i class="mdi mdi-comment-text-outline mx-0"></i> {{ count($new->getComment) }} 
                                <br><i class="mdi mdi-eye mx-0"></i> 1.5k
                            </td>
                            </div>
                            <td><div class="btn-group" role="group" aria-label="Basic example">
                                  <button type="button" title="Ubah" class="btn btn-dark btn-sm"><a href="{{ route('news.edit', $new->id) }}" style="color: white"><i class="mdi mdi-pencil"></i></a></button>
                                  <form action="{{ route('news.destroy', $new->id) }}" method="POST">
                                  @csrf
                                  @method('DELETE')
                                  <button type="submit" title="Hapus" class="btn btn-danger btn-sm"><i class="mdi mdi-delete"></i></button>
                                  </form>
                                </div>
                            </td>
                        </tr>
                       @endforeach 
                       @else
                        <tr class="bg-secondary">
                          <td colspan="6" align="center">-- Tidak Ada Data --</td>
                        </tr>
                       @endif
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
    </div>
</div>

@endsection